---
include:
  - board: ergohaven
    shield: op36_left
    snippet: studio-rpc-usb-uart
  - board: ergohaven
    shield: op36_right
  - board: ergohaven
    shield: op36_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: op36_qube-ergohaven-zmk
  - board: ergohaven
    shield: op36_left_qube

  - board: ergohaven
    shield: settings_reset
